### ISSUE TITLE
Admin report: blue screen when trying to access all questions all courses

### ISSUE THREAD

**Issue by amygroshek** [lougroshek/block_questionreport#10]
Admin report

This is a likely action, since the client requested this interface in order to download data for further analysis.

1. Select all courses, all questions
2. Select "Get the survey results"

## Selections

<img width="1092" alt="Screen Shot 2021-03-13 at 11 55 29 AM" src="https://user-images.githubusercontent.com/746182/111039322-076fef80-83f3-11eb-82e0-a4b076549976.png">

## Result

<img width="1373" alt="Screen Shot 2021-03-13 at 11 56 42 AM" src="https://user-images.githubusercontent.com/746182/111039354-48680400-83f3-11eb-964f-cfb587d48b6d.png">

**Comment by shediac2** [comment]
I am unable to replicate this on from course 148, and course 239.  No code changed.

https://learning.teachinglab.org/blocks/questionreport/adminreport.php?action=view&sid=1&cid=0&partner=&portfolio=&start_date=&end_date=&teacher=&question=100

Please retest. If problem re-occurs please enable error messages so we can track down what going on
