### ISSUE TITLE
Admin report: no results when filtering for a single course 

### ISSUE THREAD

**Issue by amygroshek** [lougroshek/block_questionreport#11]
https://learning.teachinglab.org/blocks/questionreport/adminreport.php?action=view

## Selections

<img width="1095" alt="Screen Shot 2021-03-13 at 11 58 45 AM" src="https://user-images.githubusercontent.com/746182/111039405-882eeb80-83f3-11eb-815a-bf95b66c6b0f.png">

## Result

No results in table.

<img width="1064" alt="Screen Shot 2021-03-13 at 11 59 37 AM" src="https://user-images.githubusercontent.com/746182/111039420-9aa92500-83f3-11eb-9965-4dde66067557.png">

**Comment by shediac2** [comment]
The course that was picked was course 95 - when looking at this course 
https://learning.teachinglab.org/course/view.php?id=95

There are no surveys - so I do not think this is a bug. If you want a message displaying saying that there are no results, we can do that.

I did try with course -- 148 and there is data.  So I do not think this is a bug. Please validate

**Comment by amygroshek** [comment]
Confirmed. Looks good. Thanks for checking.
