### ISSUE TITLE
Response percent is incorrect (0%) for several questions in lead facilitator report

### ISSUE THREAD

**Issue by amygroshek** [lougroshek/block_questionreport#13]
As an admin user
View lead fac report for course https://learning.teachinglab.org/blocks/questionreport/report.php?action=view&cid=M-239
Several questions have incorrect 0% in the *This Course* column

<img width="1058" alt="Screen Shot 2021-03-13 at 12 06 29 PM" src="https://user-images.githubusercontent.com/746182/111039639-b4973780-83f4-11eb-8b71-081b81b7a9fe.png">

**Comment by shediac2** [comment]
I went into course 239 - and looked at the data see screen shot. It looks like all the questions were answered with strongly disagree which would give results of 0%. 

Can you check and let me know if I am missing anything?
![Screenshot_2021-03-13 Questionnaire Report](https://user-images.githubusercontent.com/69688374/111044154-b8d34d00-8414-11eb-8867-2c9f56aa6677.png)

**Comment by amygroshek** [comment]
@shediac2 I think you were right about the 0 value mentioned above, however, when I go back and add a second student and second survey response, and all of those responses are 4 and 5, the column reads 30%. I think it should read 50%. Is that right? 
<img width="1656" alt="Screen Shot 2021-03-13 at 3 29 10 PM" src="https://user-images.githubusercontent.com/746182/111044926-051c8e00-8411-11eb-892d-6b4fcbc450f7.png">

Filtering for "Another Lead Facilitator"

<img width="1680" alt="Screen Shot 2021-03-13 at 3 30 51 PM" src="https://user-images.githubusercontent.com/746182/111044955-2f6e4b80-8411-11eb-8921-4a73dde15ad4.png">

Filtering for "Test Facilitator"

<img width="1392" alt="Screen Shot 2021-03-13 at 3 31 10 PM" src="https://user-images.githubusercontent.com/746182/111044999-5cbaf980-8411-11eb-8aed-4040f4a4aa9a.png">


Also wondering about that "-33(%)." Shouldn't that just be 0%?

**Comment by amygroshek** [comment]
I see the same issue in thePDF export, too, so can you please check there as well when implementing a fix? thanks.
